#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

export PYTHONPATH=${SCRIPT_DIR}/../src:${PYTHONPATH}

python3 ${SCRIPT_DIR}/../src/ccpn_project_checker/tests/write_cli_test_data.py "${@}"